# Информация о приложении
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  artifact-id: '@project.artifactId@'

# Параметры генерации OAS-спецификации сервиса
springdoc:
  api-docs:
    path: /api
    enabled: true
  swagger-ui:
    path: /api/doc
    layout: BaseLayout
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true
    enabled: true

# Параметры админских эндпоинтов
management:
  endpoints:
    web:
      exposure.include:
        - health
        - loggers
        - prometheus
        - info
        - mappings
      base-path: /
      path-mapping:
        prometheus: metrics
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
      group:
        liveness.include: [ "*" ]
        readiness.include: [ "*" ]
      probes:
        enabled: true
    loggers.enabled: true
    info.enabled: true
    mappings.enabled: true
    prometheus.enabled: true
    metrics.enabled: false
    beans.enabled: false
    logfile.enabled: false
    caches.enabled: false
    conditions.enabled: false
    configprops.enabled: false
    httptrace.enabled: false
    threaddump.enabled: false
    heapdump.enabled: false
    auditevents.enabled: false
    flyway.enabled: false
  health:
    defaults.enabled: false
    ping.enabled: true
  metrics:
    # Метрики на все входящие запросы по времени и количеству
    # запросов в разрезе эндпоинтов (префикс http.server.requests)
    web.server.request.autotime:
      enabled: true
      percentiles-histogram: true
    web.client.request.autotime:
      percentiles-histogram: true
    tags:
      app: ${info.name}

server:
  port: 8080

app:
  save:
    enabled: false

spring:
  application:
    name: ${info.artifact-id}

  ################### DataSource Configuration ##########################
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${APP_POSTGRESQL_HOST:localhost}:${APP_POSTGRESQL_PORT:5432}/${APP_POSTGRESQL_NAME:sber_book}?ApplicationName=${info.artifact-id}
    username: ${APP_POSTGRESQL_USER:postgres}
    password: ${APP_POSTGRESQL_PASSWORD:123456}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 4

  ################### Hibernate Configuration ##########################
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        default_schema: ${APP_POSTGRESQL_SCHEMA:sber_book}

################### logging ##########################
logging:
  level:
    root: info
